## DATASOURCE settings: set here your own configurations for the databases connection.
# Heroku PostgreSq details:
spring.datasource.url=jdbc:postgres://ec2-54-74-35-87.eu-west-1.compute.amazonaws.com:5432/de7h3tjk18cuig
spring.datasource.username=tikmskrpanmfbl
spring.datasource.password=3d9549eb719f8f6d57286d284de0030ce9a11ae3f1c40690fe3a8c1def61bd9b

# Hibernate ddl auto (create, create-drop, validate, update):
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=
server.port=${PORT:8080}


spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.date-format=(yyyy-MM-dd)

## SESSION PROPERTIES
# MAX inactive interval in minutes
session.max.inactive.interval=30
# Time interval to check expired session in seconds
session.remove.expired.period=20

## MULTIPART properties
# Enable multipart ulpoads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk
spring.servlet.multipart.file-size-threshold=2KB
# MAX file size
spring.servlet.multipart.max-file-size=1MB
# MAX request size
spring.servlet.multipart.max-request-size=10MB

## FILE STORAGE PROPERTIES
file.upload-dir=src/main/resources/static/assets
